package com.shubhi.date_testing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class data_object implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public data_object() {
    }




}